#!/usr/bin/env sh
set -e

echo "Running RuboCop before commit..."
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.rb$' || true)
if [ -n "$STAGED_FILES" ]; then
  bin/rubocop $STAGED_FILES
else
  echo "No Ruby files staged, skipping RuboCop."
fi
